config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :accounts, except: [:destroy] do
    collection do
      get :suggestions
      get :at_date
    end
    member do
      get :months
    end
    resources :transactions, controller: 'account_transactions', only: [:index, :new, :create, :show]
    resources :reports, controller: 'account_reports', only: [:index, :show]
    member do
      get :webhook_logs
    end
  end

  # All transactions
  resources :transactions do
    collection do
      get :pending_webhooks
    end
    member do
      post :notify
    end
  end
  resources :categories
  resources :invoices
  resources :policies
  resources :logs, only: [:index]
end

app/models/openbill/invoice.rb
module Openbill
  class Invoice < Sequel::Model(INVOICES_TABLE_NAME)
    many_to_one :destination_account, class: 'Openbill::Account'

    def amount
      Money.new amount_cents, amount_currency
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    render locals: { invoices: invoices }
  end

  def new
    render locals: { invoice: InvoiceForm.new }
  end

  def show
    respond_to do |format|
      format.html do
        render locals: { invoice: invoice }
      end
      format.pdf do
        render pdf: 'show.pdf', locals: { invoice: invoice }, layout: false
      end
    end
  end

  def edit
    invoice_form = InvoiceForm.new invoice
    render :edit, locals: { invoice: invoice_form }
  end

  def create
    invoice_form = InvoiceForm.new permitted_params

    if invoice_form.valid?
      invoices.insert invoice_form.to_hash
      redirect_to invoices_path
    else
      render :new, locals: { invoice: invoice_form }
    end

  rescue => err
    flash.now[:error] = err.message
    render :new, locals: { invoice: invoice_form }
  end

  def update
    invoice_form = InvoiceForm.new({ **permitted_params.symbolize_keys, id: invoice.id })

    if invoice_form.valid?
      invoice.update invoice_form.to_hash
      redirect_to invoices_path
    else
      render :edit, locals: { invoice: invoice_form }
    end

  rescue => err
    flash.now[:error] = err.message
    render :edit, locals: { invoice: invoice_form }
  end

  def destroy
    invoice.delete
    redirect_to :back
  rescue => err
    redirect_to :back, flash: { error: err.message }
  end

  private

  def invoice
    OpenbillInvoice.find params[:id]
  end

  def permitted_params
    params.require(:invoice).permit(:date, :number, :title, :destination_account_id, :amount_cents, :amount_currency)
  end

  def invoices
    @_invoices ||= OpenbillInvoice.order('id desc')
  end
end

app/views/invoices/_form.html.slim
= simple_form_for invoice do |f|
  .row
    .col-md-6
      = f.input :date, as: :date_picker, readonly: true
    .col-md-6
      = f.input :number
  .row
    .col-md-6
      = f.input :title
    .col-md-6
      = f.input :destination_account_id
  .row
    .col-md-6
      = f.input :amount_cents
    .col-md-6
      = f.input :amount_currency, collection: currencies_collection, include_blank: false
  = f.submit class: 'btn btn-success'

app/views/invoices/_invoice.slim
.row
  .col-md-1
    b Id
  .col-md-6= invoice.id
.row
  .col-md-1
    b Number
  .col-md-6= invoice.number
.row
  .col-md-1
    b Title
  .col-md-6= invoice.title
.row
  .col-md-1
    b Destination account id
  .col-md-6= link_to invoice.destination_account_id, account_path(invoice.destination_account_id)
.row
  .col-md-1
    b Date
  .col-md-6= humanized_date invoice.date
.row
  .col-md-1
    b Amount
  .col-md-6= humanized_amount invoice.amount

app/views/invoices/edit.html.slim
h1
  ' Edit Invoice

.m-t-3
  = render 'form', invoice: invoice

app/views/invoices/index.html.slim
h1
  | Invoices
  .pull-xs-right= link_to 'New invoice', new_invoice_path, class: 'btn btn-sm btn-success'

table.table.table-condensed.table-striped.m-t-3
  thead.thead-default
    tr
      th UUID
      th Date
      th Number
      th Amount
      th Created at
      th
        .pull-xs-right= t :actions
  tbody
    - invoices.each do |invoice|
      tr
        td
          = link_to invoice.id, edit_invoice_path(invoice.id)
        td= humanized_date invoice.date
        td= invoice.number
        td= humanized_amount invoice.amount
        td= humanized_date invoice.created_at

        td.pull-xs-right
          .btn-group
            = destroy_button invoice_path(invoice.id)
            = link_to t('show.html'), invoice_path(invoice.id, format: :html), target: '_blank', class: 'btn btn-sm btn-info'
            = link_to t('show.pdf'), invoice_path(invoice.id, format: :pdf), target: '_blank', class: 'btn btn-sm btn-info'

app/views/invoices/new.html.slim
h1 New invoice

.m-t-3
  = render 'form', invoice: invoice

app/views/invoices/show.html.slim
= render 'invoice', invoice: invoice
p
  = link_to t('show.pdf'), invoice_path(invoice.id, format: :pdf), target: '_blank', class: 'btn btn-sm btn-info'

app/views/invoices/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body>
    <div id="content">
      <%= render 'invoice', invoice: invoice %>
    </div>
  </body>
</html>