config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :accounts, except: [:destroy] do
    collection do
      get :suggestions
      get :at_date
    end
    member do
      get :months
    end
    resources :transactions, controller: 'account_transactions', only: [:index, :new, :create, :show]
    resources :reports, controller: 'account_reports', only: [:index, :show]
    member do
      get :webhook_logs
    end
  end

  # All transactions
  resources :transactions do
    collection do
      get :pending_webhooks
    end
    member do
      post :notify
    end
  end
  resources :categories
  resources :invoices
  resources :policies
  resources :logs, only: [:index]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  helper_method :filter

  def index
    respond_to do |format|
      format.html {
        render locals: {
          transactions: transactions.page(page).per(per_page),
          transactions_count: transactions.count,
          ransack: ransack
        }
      }

      format.csv {
        content = TransactionsSpreadsheet.new(transactions).to_csv
        send_data(
            content,
            disposition: 'attachment; filename=transactions.csv',
            type: 'text/csv'
        )
      }
    end
  end

  def pending_webhooks
    render locals: {
      transactions: pending_webhooks_transactions.includes(:to_account, :from_account, :last_webhook_log).page(page).per(per_page),
      transactions_count: transactions.count
    }
  end

  def new
    if reverse_transaction.present?
      transaction.amount_cents = reverse_transaction.amount.to_f
      transaction.amount_currency = reverse_transaction.amount_currency
      transaction.from_account_id = reverse_transaction.to_account_id
      transaction.to_account_id = reverse_transaction.from_account_id
      transaction.key = reverse_transaction.key + '-reverse'
      transaction.date = reverse_transaction.date
      transaction.details = "Reverse of #{reverse_transaction.details}"
    end
    render locals: { transaction: OpenbillTransaction.new(permitted_params) }
  end

  def edit
    transaction.update permitted_params
    render :new, locals: { transaction: transaction }
  end

  def create
    transaction = OpenbillTransaction.new permitted_params
    if transaction.save
      redirect_to transactions_path
    else
      render :new, locals: { transaction: transaction }
    end
  end

  def update
    transaction.update permitted_params
    if transaction.valid?
      redirect_to transactions_path
    else
      render :new, locals: { transaction: transaction }
    end
  end

  def notify
    flash[:success] = "Transaction #{transaction.id} is notified"
    transaction.notify!
    redirect_to :back
  end

  def show
    render locals: { transaction: transaction }
  end

  def destroy
    transaction.destroy!
    redirect_to transactions_path
  rescue => err
    redirect_to transactions_path, flash: { error: err.message }
  end

  private

  def transaction
    @transaction ||= Transaction.find params[:id]
  end

  def date
    return unless params.key?(:transaction)
    TransactionDate.parse permitted_params
  end

  def reverse_transaction
    return nil unless permitted_params[:reverse_transaction_id].present?
    OpenbillTransaction.find permitted_params[:reverse_transaction_id]
  end

  def transaction
    OpenbillTransaction.find params[:id]
  end

  def ransack
    OpenbillTransaction.ransack params[:q]
  end

  def transactions
    ransack.result.includes(:to_account, :from_account).order('created_at asc')
  end

  def pending_webhooks_transactions
    # TODO
    raise 'todo'
    filter.apply(OpenbillTransaction.get_pending_webhooks_transactions)
  end

  def permitted_params
    return {} unless params[:transaction].present?
    # Allow any parameters
    params.require(:transaction).permit!
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_filter.slim
.mb-4.mt-4
  = search_form_for ransack, url: transactions_path, method: 'get' do |f|
    -# = f.hidden_field :order
    .row
      .col-md-6
        = select_account_field f, :from_account_id_or_to_account_id_eq, include_blank: '*', required: false
        = select_account_field f, :from_account_id_eq, include_blank: '*', required: false
        = select_account_field f, :to_account_id_eq, include_blank: '*', required: false
        .row
          .col-md-6
            = f.input :date_gteq, as: :date_picker, readonly: true, required: false
          .col-md-6
            = f.input :date_lteq, as: :date_picker, readonly: true, required: false
      .col-md-6
        .row
          .col-md-6
            = f.input :amount_cents_lteq, required: false
          .col-md-6
            = f.input :amount_cents_gteq, required: false

        = f.input :key_cont, required: false
        = f.input :details_cont, required: false
    = f.button :submit, 'Найти', class: 'btn btn-primary'
    - if params[:q].present?
      = link_to 'Сбросить фильтр', accounts_path, class: 'btn btn-default'

app/views/transactions/_form.slim
- if transaction.reverse_transaction_id.present?
  h2 Make a reverse transaction
= simple_form_for transaction do |f|
  = f.input :reverse_transaction_id, as: :hidden
  .row
    .col-md-6
      = select_account_field f, :from_account_id
    .col-md-6
      = select_account_field f, :to_account_id
  .row
    .col-md-6
      = f.input :amount_cents
    .col-md-6
      = f.input :amount_currency, collection: currencies_collection, include_blank: false
  .row
    .col-md-3
      = f.input :date, as: :date_picker, readonly: true
    .col-md-3
      = f.input :key
    .col-md-3
      = f.input :details, as: :text
    .col-md-3
      = f.input :meta

  = f.submit class: 'btn btn-success'

app/views/transactions/index.slim
.pull-right
  = link_to 'Pending webhooks', pending_webhooks_transactions_path, class: 'btn btn-sm btn-default'
  | &nbsp;
  = link_to 'Export to CSV', transactions_path(request.query_parameters.merge format: :csv), class: 'btn btn-sm btn-default', target: '_blank'
  | &nbsp;
  = link_to 'New transaction', new_transaction_path, class: 'btn btn-sm btn-success'
h1
  | Transactions (#{transactions_count})

= render 'filter', ransack: ransack
= render 'pagination', scope: transactions

- if transactions.any?
  table.table.table-condensed.table-striped
    thead
      tr
        th= sort_link ransack, :created_at, label: 'Create time'
        th= sort_link ransack, :date, label: 'Record date'
        th= sort_link ransack, :from_account_id, label: 'Source account'
        th= sort_link ransack, :to_account_id, label: 'Destination account'
        th= sort_link ransack, :amount_cents, label: 'Amount'
        th= sort_link ransack, :key
        th Details
        th Meta
        th Webhook state
        th Actions

    tbody
    - transactions.each do |t|
      tr
        td
          = link_to transaction_path t.id do
            .text-nowrap= I18n.l t.created_at, format: :short
        td= humanized_date t.date
        td
          = link_to t.from_account, account_path(t.from_account_id)
          div
            small.text-muted= t.from_account.details
        td
          = link_to t.to_account, account_path(t.to_account_id)
          div
            small.text-muted= t.to_account.details
        td= humanized_amount t.amount
        td
          code = t.key
        td
          .text-muted= t.details
        td= humanized_meta t.meta
        td
          - if webhook_presents?
            - if t.last_webhook_log.present?
              = link_to t.last_webhook_log.message, logs_path(transaction_id: t.id)
        td
          = show_button transaction_path(t.id)
          - if t.reverse_transaction_id.present?
            br
            = link_to "Reversed (Original transaction)", transaction_path(t.reverse_transaction_id)

- else
  .mt-4.alert.alert-info Нет транзакций по такому запросу
hr

= render 'pagination', scope: transactions

app/views/transactions/new.html.slim
h1 New transaction

.m-t-3
  = render 'form', transaction: transaction

app/views/transactions/pending_webhooks.slim
h1
  | Pending webhooks transactions (#{transactions_count})

= render 'filter'
= render 'pagination', scope: transactions

table.table.table-condensed.table-striped
  thead
    tr
      th= order_by filter, :created_at, label: 'Create time'
      th= order_by filter, :date, label: 'Record date'
      th= order_by filter, :from_account_id, label: 'Source account'
      th= order_by filter, :to_account_id, label: 'Destination account'
      th= order_by filter, :amount_cents, label: 'Amount'
      th= order_by filter, :key
      th Details
      th Meta
      th Webhook state
      th Actions

  tbody
  - transactions.each do |t|
    tr
      td
        = link_to transaction_path t.id do
          .text-nowrap= I18n.l t.created_at, format: :short
      td= humanized_date t.date
      td
        = link_to t.from_account, account_path(t.from_account_id)
        div
          small.text-muted= t.from_account.details
      td
        = link_to t.to_account, account_path(t.to_account_id)
        div
          small.text-muted= t.to_account.details
      td= humanized_amount t.amount
      td
        code = t.key
      td
        .text-muted= t.details
      td= humanized_meta t.meta
      td
        - if t.last_webhook_log.present?
          = link_to t.last_webhook_log.message, logs_path(transaction_id: t.id)
      td
        = show_button transaction_path(t.id)
        - if t.reverse_transaction_id.present?
          br
          = link_to "Reversed (Original transaction)", transaction_path(t.reverse_transaction_id)

hr

= render 'pagination', scope: transactions

app/views/transactions/show.slim
h1
  | Transaction (#{transaction.id})
p
  = notify_button notify_transaction_path(transaction.id)
  = edit_button edit_transaction_path(transaction.id)
  = destroy_button transaction_path(transaction.id)

- if transaction.reverse_transaction_id.present?
  = link_to "Original transaction", transaction_path(transaction.reverse_transaction_id)
- elsif transaction.reversation_transaction.present?
  = link_to 'Reversation transaction', transaction_path(transaction.reversation_transaction.id)
- else
  = link_to 'Reverse', new_transaction_path(transaction: { reverse_transaction_id: transaction.id })

.row
  .col-md-6
    div style="padding: 1.5em"
      dl.dl-horizontal
        dt.col-sm-3 Created at
        dd.col-sm-9= I18n.l transaction.created_at, format: :short
        dt.col-sm-3 Record date
        dd.col-sm-9= humanized_date transaction.date
        dt.col-sm-3 Key
        dd.col-sm-9= transaction.key
        dt.col-sm-3 From account
        dd.col-sm-9
          = link_to transaction.from_account, account_path(transaction.from_account_id)
        dt.col-sm-3 To account
        dd.col-sm-9
          = link_to transaction.to_account, account_path(transaction.to_account_id)

  .col-md-6
    div style="padding: 1.5em"
      dl.dl-horizontal
        dt.col-sm-3 Amount
        dd.col-sm-9= humanized_amount transaction.amount
        dt.col-sm-3 Details
        dd.col-sm-9= transaction.details
        dt.col-sm-3 Meta
        dd.col-sm-9.text-muted= humanized_meta transaction.meta
        dt.col-sm-3 Username
        dd.col-sm-9= transaction.username