config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :accounts, except: [:destroy] do
    collection do
      get :suggestions
      get :at_date
    end
    member do
      get :months
    end
    resources :transactions, controller: 'account_transactions', only: [:index, :new, :create, :show]
    resources :reports, controller: 'account_reports', only: [:index, :show]
    member do
      get :webhook_logs
    end
  end

  # All transactions
  resources :transactions do
    collection do
      get :pending_webhooks
    end
    member do
      post :notify
    end
  end
  resources :categories
  resources :invoices
  resources :policies
  resources :logs, only: [:index]
end

app/views/layouts/_messages.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert alert-#{name.to_sym}"]
      a.close[data-dismiss='alert'] ×
      div= msg

app/views/layouts/_topmenu.slim
nav.navbar.navbar-expand-lg.bg-body-tertiary.sticky-top.border-bottom
  = content_tag :div, class: "#{defined?(container_class) ? container_class : 'container-fluid'} px-3" do
    span.navbar-brand.mb-0.h1
      = link_to root_url, class: 'text-dark text-decoration-none' do
        = render 'logo'
    button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0.d-flex
        = navbar_link_to OpenbillAccount.model_name.human(count: 2), accounts_path
        = navbar_link_to OpenbillTransaction.model_name.human(count: 2), transactions_path
        = navbar_link_to OpenbillCategory.model_name.human(count: 2), categories_path
        = navbar_link_to OpenbillPolicy.model_name.human(count: 2), policies_path
        = navbar_link_to OpenbillInvoice.model_name.human(count: 2), invoices_path

app/views/layouts/application.slim
doctype html
html
  = render 'head'
  body
    = render 'layouts/topmenu'
    main#content.container-fluid
      = render 'layouts/messages'
      = yield