config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :accounts, except: [:destroy] do
    collection do
      get :suggestions
      get :at_date
    end
    member do
      get :months
    end
    resources :transactions, controller: 'account_transactions', only: [:index, :new, :create, :show]
    resources :reports, controller: 'account_reports', only: [:index, :show]
    member do
      get :webhook_logs
    end
  end

  # All transactions
  resources :transactions do
    collection do
      get :pending_webhooks
    end
    member do
      post :notify
    end
  end
  resources :categories
  resources :invoices
  resources :policies
  resources :logs, only: [:index]
end

app/models/openbill/account.rb
class Openbill::Account < ApplicationRecord
  belongs_to :category, class_name: 'OpenbillCategory'

  def amount
    Money.new amount_cents, amount_currency
  end

  def date_amount
    Money.new date_amount_cents, amount_currency
  end

  def date_amount_cents
    values[:date_amount_cents]
  end

  def <=> (other)
    id <=> other.id
  end

  def to_s
    key
  end

  def self.at_date(date)
    dataset
      .select_all(:openbill_accounts)
      .left_join(
    Sequel.as(:openbill_transactions, :t1),
    [
      Sequel.lit('t1.date <= ?', date),
      Sequel.or(
        t1__from_account_id: :openbill_accounts__id,
        t1__to_account_id: :openbill_accounts__id
      )
    ]
    )
      .select_append(
    Sequel.as(
      Sequel.lit('SUM(COALESCE((CASE openbill_accounts.id WHEN t1.from_account_id THEN -t1.amount_cents ELSE t1.amount_cents END)::bigint, 0))'),
      :date_amount_cents
    )
    )
      .group(:openbill_accounts__id)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  DEFAULT_CATEGORY_ID = '12832d8d-43f5-499b-82a1-3466cadcd809'

  helper_method :filter, :filter_params, :current_category

  def index
    periods = build_periods

    respond_to do |format|
      format.html do
        render locals: {
          periods: periods,
          accounts: accounts,
          categories: categories,
          ransack: ransack,
          current_category: current_category,
        }
      end
      format.csv do
        content = AccountsSpreadsheet.new(accounts, periods).to_csv
        send_data(
            content,
            disposition: 'attachment; filename=accounts.csv',
            type: 'text/csv'
        )
      end
    end
  end

  def months
    periods = build_periods use_previous: false

    accounts = {}

    opposite_account_type = account.amount < 0 ? :to_account : :from_account
    opposite_account_id = "#{opposite_account_type}_id"
    periods.each do |period|
      account.
        all_transactions.
        by_month(period.last).
        includes(opposite_account_type).
        group(opposite_account_id).
        sum(:amount_cents).
        each do |account_id, amount_cents|
        a = accounts[account_id] ||= OpenStruct.new(
          account: OpenbillAccount.find(account_id),
          periods: {}
        )
        a.periods[period] = Money.new amount_cents, account.amount_currency
      end
    end

    accounts = accounts.each_value

    respond_to do |format|
      format.html do
        render locals: {
          periods: periods,
          account: account,
          accounts: accounts
        }
      end
      format.csv do
        content = AccountReportSpreadsheet.new(accounts, periods).to_csv
        send_data(
            content,
            disposition: "attachment; filename=account_#{account.id}_report.csv",
            type: 'text/csv'
        )
      end
    end
  end

  def suggestions
    accounts = OpenbillAccount.order(:key).where("key like ?", "#{params[:q]}%")
    render json: {
      total_count: accounts.count,
      items: accounts.map { |c| { id: c.id, text: "#{c.name} (#{c.details})" }}
    }
  end

  def at_date
    render locals: {
      accounts: accounts,
      ransack: ransack,
      current_category: current_category,
      categories: categories
    }
  end

  def new
    render locals: { account: OpenbillAccount.new }
  end

  def show
    transactions_ransack = account.all_transactions.ransack params[:q]

    transactions = transactions_ransack.result.ordered.page(page).per(per_page)
    render locals: {
      account: account,
      transactions_ransack: transactions_ransack,
      transactions: transactions
    }
  end

  def edit
    render locals: { account: account, account_key: account.key }
  end

  def create
    account = OpenbillAccount.new permitted_params

    if account.save
      redirect_to accounts_path
    else
      render :new, locals: { account: account }
    end

  rescue => err
    flash.now[:error] = err.message
    render :new, locals: { account: account }
  end

  def update
    account.update permitted_params

    if account.valid?
      redirect_to accounts_path
    else
      render :edit, locals: { account_key: account.key, account: account }
    end

  rescue => err
    flash.now[:error] = err.message
    render :edit, locals: { account_key: account.key, account: account }
  end

  def webhook_logs
    render locals: { logs: logs, db_error: @db_error }
  end

  private

  def logs
    query = WebhooksQuery.new(filter: webhooks_filter).call
    filter.apply(query).paginate page, per_page
  end

  def webhooks_filter
    WebhooksFilter.new(
      account: account
    )
  end

  def ransack
    OpenbillAccount.ransack params[:q]
  end

  def accounts
    all_accounts.page(page).per(per_page)
  end

  def all_accounts
    ransack.result.ordered
  end

  def account
    @_account ||= OpenbillAccount.find params[:id]
  end

  def current_category
    id  =params.fetch(:q, {})[:category_id_eq]
    return unless  id
    OpenbillCategory.find id
  end

  def categories
    @_categories ||= OpenbillCategory.all
  end

  def permitted_params
    params.require(:account).permit(:key, :category_id, :amount_currency, :details, :meta)
  end

  def start_date
    OpenbillTransaction.order('created_at asc').first.try(:created_at).try(:date) || Date.today
  end

  def build_periods(count: 5, use_previous: true)
    today = Date.today
    periods = [Period.new(today.beginning_of_month, today.end_of_month)]
    count.times do
      period = periods.last
      first = (period.first - 1.day).beginning_of_month
      last = first.end_of_month
      periods.push Period.new(first, last)
    end

    period = periods.last.last
    periods.push Period.new(nil, (period.beginning_of_month - 1.day).end_of_month) if use_previous

    periods.reverse
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def select_account_field(form, key, include_blank: false, required: false)
    form.input(
      key,
      as: :select,
      collection: accounts_selected_collection(form.object.send(key)),
      include_blank: include_blank,
      input_html: { data: { accounts: true }},
      required: false
    )
  end

  def accounts_selected_collection(account_id)
    return [] unless account_id
    account = OpenbillAccount.find account_id
    [account]
  end

  def opposite_account_hint(account_id)
    return if account_id.blank? || account_id.to_s == 'total'

    account = OpenbillAccount.find account_id

    link_to "#{account.key} (#{account.details})", account_path(account_id)
  end

  def income_transaction_button(income_account: )
    link_to fa_icon(:plus), new_account_transaction_path(income_account.id, direction: :income), class: 'btn btn-sm btn-success'
  end

  def outcome_transaction_button(outcome_account: )
    link_to fa_icon(:minus), new_account_transaction_path(outcome_account.id, direction: :outcome), class: 'btn btn-sm btn-danger'
  end

  def account_title(account)
    "#{account.category}/#{account.key} (#{account.details})"
  end

  def accounts_collection
    OpenbillAccount.find_each.map do |acc|
      account_select_item acc
    end
  end

  def account_select_item(acc)
    ["#{acc.key} [#{acc.details}]", acc.id]
  end
end

app/views/accounts/_categories.slim
ul.nav.nav-pills
  li.nav-item
    = link_to "All (#{accounts_count})", accounts_path, class: current_category.blank? ? 'nav-link active' : 'nav-link'
  - categories.each do |cat|
    li.nav-item
      = link_to "#{cat.name} (#{accounts_count(cat)})", accounts_path(q: { category_id_eq: cat.id }), class: current_category.try(:id) == cat.id ? 'nav-link active' : 'nav-link'
br

app/views/accounts/_date_categories.slim
ul.nav.nav-pills
  li.nav-item
    = link_to "All (#{accounts_count})", at_date_accounts_path(philtre: { category_id: nil }), class: current_category.try(:id).blank? ? 'nav-link active' : 'nav-link'
  - categories.each do |cat|
    li.nav-item
      = link_to "#{cat.name} (#{accounts_count(cat)})", at_date_accounts_path(philtre: { category_id: cat.id }), class: current_category.try(:id) == cat.id ? 'nav-link active' : 'nav-link'
br

app/views/accounts/_date_filter.slim
= simple_form_for filter.for_form, url: at_date_accounts_path, method: 'get' do |f|
  = f.hidden_field :order
  .row
    .col-md-6
      = f.input :date, as: :date_picker, readonly: true, required: false
  = f.button :submit
  = link_to 'Reset', at_date_accounts_path, class: 'btn btn-default'
br

app/views/accounts/_filter.slim
.mb-4.mt-2
  = link_to 'Показать фильтр', '#filter', class: 'btn btn-sm btn-outline-primary', data: { toggle: :collapse }, 'aria-expanded': false, 'aria-controls': 'collapseExample'

  #filter.mt-3.mb-2.collapse class=(params[:q].blank? ? '' : 'show')
    = search_form_for ransack, url: accounts_path, method: 'get' do |f|
      /-# = f.hidden_field :order
      .row
        .col-md-6
          = f.input :key_cont, required: false, as: :search
          = f.input :details_cont, required: false, as: :search
        .col-md-3
          = f.input :amount_cents_lteq, as: :numeric, required: false
        .col-md-3
          = f.input :amount_cents_gteq, as: :numeric, required: false
      .mt-2
        = f.button :submit, 'Найти', class: 'btn btn-primary'
        - if params[:q].present?
          = link_to 'Сбросить фильтр', accounts_path, class: 'btn btn-default'

app/views/accounts/_header.slim
.mt-1
  = edit_button edit_account_path(account.id)
  -#= link_to t(:webhooks), webhook_logs_account_path(account.id), class: 'btn btn-sm btn-info'
  = link_to t(:reports), account_reports_path(account.id), class: 'btn btn-sm btn-info'
  = link_to 'months', months_account_path(account.id), class: 'btn btn-default'
  = export_csv_link
  = render 'account_actions', account: account
h1
  | Account
  = link_to "##{account.key}", account_path(account.id)
p= account.details

.clearfix

app/views/accounts/_transactions.slim
- if transactions.any?
  h2 Transactions (#{account.transactions_count})

  = render 'pagination', scope: transactions
  table.table.table-condensed.table-striped
    thead
      tr
        th= sort_link ransack, :created_at, label: 'Time'
        th= sort_link ransack, :date, label: 'Record date'
        th Opposite account
        th= sort_link ransack, :amount_cents, label: 'Amount'
        th= sort_link ransack, :key
        th Details
        th Meta
        th Actions

    = render 'transactions_table_body', transactions: transactions, account: account
  hr
  = render 'pagination', scope: transactions

- else
  p.lead No transactions

app/views/accounts/_transactions_table_body.slim
tbody
  - transactions.each do |transaction|
    - t = AccountTransaction.new account, transaction
    tr
      td
        = link_to transaction_path t.id do
          .text-nowrap= I18n.l t.created_at, format: :short
      td.text-nowrap= humanized_date t.date
      td
        = link_to t.opposite_account, account_path(t.opposite_account.id)
        div
          small.text-muted= t.opposite_account.details
      td= humanized_amount t.amount
      td
        code = t.key
      td
        .text-muted= t.details
      td= humanized_meta t.meta
      td
        = link_to 'Show', transaction_path(t.id)
        - if t.reverse_transaction_id.present?
          br
          = link_to "Reversed (Original transaction)", transaction_path(t.reverse_transaction_id)

app/views/accounts/_webhooks_table.slim
table.table.table-condensed.table-striped
  thead
    tr
      th.col-md-1= order_by filter, :created_at, label: 'Time'
      th.col-md-3 Message
      th.col-md-2= order_by filter, :url
      th.col-md-3= order_by filter, :transaction_id, label: 'Transaction'
      th.col-md-1= order_by filter, :status
      th.col-md-2 Body

  tbody
    - logs.each do |l|
      tr
        td.col-md-1
          p = I18n.l l[:created_at], format: :short
          small.text-muted= l[:pid]
        td.col-md-3= l[:message]
        td.col-md-2= l[:url]
        td.col-md-3= l[:transaction_id]
        td.col-md-1= l[:status]
        td.col-md-2 = l[:body]

app/views/accounts/at_date.slim
h1
  | Accounts at date
  .pull-xs-right= link_to 'New account', new_account_path, class: 'btn btn-sm btn-success'

= render 'date_categories', categories: categories

-# = render 'date_filter', ransack: ransack, category: current_category
= render 'pagination', scope: accounts

table.table.table-condensed.table-striped
  thead.thead-default
    tr
      th= sort_link ransack, :key
      th= sort_link ransack, :amount_cents
      - if accounts.any? { |a| a.date_amount_cents.present? }
        th Amount at date
      th= sort_link ransack, :updated_at
      th= sort_link ransack, :transactions_count
      th= t :meta
      th
        .pull-xs-right= t :actions
  tbody
    - accounts.each do |account|
      tr
        td
          = link_to account.key, account_path(account.id)
          br
          small.text-muted
            = account.details
        td= humanized_amount account.amount
        - if account.date_amount_cents.present?
          td= humanized_amount account.date_amount
        td= l account.updated_at, format: :short
        td= link_to account.transactions_count, account_path(account.id)
        td.text-muted= humanized_meta account.meta
        td  style="min-width: 180px"
          .pull-xs-right
            = render 'account_actions', account: account

hr

= render 'pagination', scope: accounts

app/views/accounts/index.html.slim
.pull-right
  /= link_to 'Accounts at date', at_date_accounts_path, class: 'btn btn-sm btn-default'
  /| &nbsp;
  = export_csv_link
  | &nbsp;
  = link_to t(:new_account, scope: :buttons), new_account_path, class: 'btn btn-sm btn-success'

h2.mb-4 Счета (#{accounts.count} из #{OpenbillAccount.count})
= render 'categories', categories: categories, current_category: current_category

.pull-right
  = render 'pagination', scope: accounts

= render 'filter', ransack: ransack, category: current_category
- if action_name == 'index'
  = render 'list', ransack: ransack, accounts: accounts, periods: periods
- elsif index_type.graph?
  = render 'table', ransack: ransack, accounts: accounts
- else
  p Unknown index type #{index_type}

.pull-right
  = render 'pagination', scope: accounts

app/views/accounts/months.html.slim
= render 'header', account: account

table.table.table-condensed.table-stripped
  thead
    tr
      th Аккаунт
      - periods.each do |m|
        th= humanized_period m
  tbody
    - accounts.each do |a|
      tr
        td
          = render 'account_link', account: a.account
        - periods.each do |period|
          td= humanized_amount a[:periods][period]

app/views/accounts/new.html.slim
h1.mb-3 New account

= render 'form', account: account

app/views/accounts/show.html.slim
= render 'header', account: account

= simple_form_for transactions_ransack, url: account_path(id: account.id), method: 'get' do |f|
  .row
    .col-md-6
      = f.input :date, as: :date_picker, readonly: true
  = f.button :submit
br

.row
  .col-md-6
    div style="padding: 1.5em"
      dl.dl-horizontal
        /- if account.date_amount_cents.present?
          /dt.col-sm-3 Amount for date
          /dd.col-sm-9= humanized_amount account.date_amount
        dt.col-sm-3 Amount
        dd.col-sm-9= humanized_amount account.amount
        dt.col-sm-3 Details
        dd.col-sm-9= account.details
        dt.col-sm-3 Meta
        dd.col-sm-9.text-muted= humanized_meta account.meta
  .col-md-6
    div style="padding: 1.5em"
      dl.dl-horizontal
        dt.col-sm-3 ID
        dd.col-sm-9= account.id
        dt.col-sm-3 Category
        dd.col-sm-9
          = link_to account.category, category_path(account.category_id)

.row
  .col-md-12

    = render 'transactions', transactions: transactions, account: account, ransack: transactions_ransack

app/views/accounts/webhook_logs.slim
h1 Webhook logs

- if db_error.present?
  .alert.alert-danger= db_error

- else
  = render 'webhooks_table', logs: logs

  hr

  = render 'pagination', scope: logs